name: Gian workflow
on:
  push:
    branches:
      - gian_branch

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: node ./scripts/build.js
