name: A workflow for my Hello World file
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Hello world action
        run: echo "Hello world!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REF: ${{ github.ref }}
          GITHUB_EVENT_NAME: ${{ github.eventName }}
          GITHUB_WORKFLOW: ${{ github.workflow }}
          GITHUB_ACTION: ${{ github.action }}
      - uses: ./action-a
        with:
          MY_NAME: "Lucas"
      - uses: ./action-b
